spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/data-jpa  # 임베디드 메모리 데이터베이스 (다른 옵션: jdbc:h2:file:./data/testdb)
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 데이터베이스 스키마 자동 생성/업데이트 (none, update, create, create-drop)
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 포맷팅

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace
